# Generated by Django 2.0.2 on 2018-04-13 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrugSystem', '0002_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drugs',
            name='order',
        ),
        migrations.AddField(
            model_name='orders',
            name='drugs',
            field=models.ManyToManyField(to='DrugSystem.Drugs'),
        ),
    ]
