# Generated by Django 2.0.4 on 2018-04-13 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrugSystem', '0003_auto_20180413_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugs',
            name='DEALvl',
            field=models.CharField(default='CI', max_length=10),
        ),
        migrations.AddField(
            model_name='drugs',
            name='dosageFormName',
            field=models.CharField(default='NOName', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drugs',
            name='productTypeName',
            field=models.CharField(default='NONAME', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='drugs',
            name='NDC',
            field=models.CharField(db_index=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='drugs',
            name='name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='drugs',
            name='quanity',
            field=models.IntegerField(default=100),
        ),
    ]
