# Generated by Django 2.0.4 on 2018-04-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrugSystem', '0004_auto_20180413_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugs',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='drugs',
            name='dosageFormName',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='drugs',
            name='productTypeName',
            field=models.TextField(),
        ),
    ]
