# Generated by Django 2.0.4 on 2018-04-13 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrugSystem', '0005_auto_20180413_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugs',
            name='dosageFormName',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='drugs',
            name='name',
            field=models.TextField(),
        ),
    ]
