# Generated by Django 2.0.4 on 2018-04-13 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DrugSystem', '0006_auto_20180413_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugs',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='DrugSystem.Client'),
        ),
    ]
