# Generated by Django 2.0.2 on 2018-04-17 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DrugSystem', '0007_drugs_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drugs',
            name='user',
        ),
        migrations.AddField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='DrugSystem.Client'),
        ),
    ]
