# Generated by Django 2.0.2 on 2018-04-17 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrugSystem', '0008_auto_20180417_0544'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='confirmNum',
            field=models.TextField(default='1afda'),
        ),
    ]
