# Generated by Django 2.0.2 on 2018-04-17 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrugSystem', '0009_orders_confirmnum'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='isDelivered',
            field=models.BooleanField(default=False),
        ),
    ]
