# Generated by Django 2.0.2 on 2018-04-17 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrugSystem', '0010_orders_isdelivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='location',
            field=models.TextField(default='Shipping Factilite'),
            preserve_default=False,
        ),
    ]
