# Generated by Django 2.0.2 on 2018-04-17 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrugSystem', '0011_orders_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orders',
            name='confirmNum',
            field=models.TextField(),
        ),
    ]
